In [1]:
# autoreload modules when code is run. Otherwise, python will not see recent changes. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
filename = 'new_debt_data.xlsx'
pd.read_excel(filename).head(5)

,"Government deficit and debt in the EU-countries by unit, function, country and time",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,Units: -,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,2000.0,2001.0,2002.0,2003.0,2004.0,2005.0,2006.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
2,Mill. Euro (current prices),Government EMU-debt,Belgium,280959.5,286055.5,288110.8,285866.7,288418.8,294975.3,297494.9,...,414432.4,431384.3,438504.8,451619.9,454048.4,459388.5,467249.4,515211.9,548456.4,578063.2
3,NaN,NaN,Bulgaria,10177.1,10269.8,8890.3,8126.5,7526.2,6388.6,5721.0,...,7147.6,11619.3,11871.6,14188.1,13182.6,12427.2,12311.1,15131.7,17013.2,19352.9
4,NaN,NaN,Cyprus,6024.5,6660.9,7339.8,8184.8,9055.9,9595.9,9597.7,...,18706.5,19013.8,19296.8,19631.5,18935.6,21343.9,21565.9,25388.1,24744.7,23767.3

In [3]:
debt = pd.read_excel(filename, skiprows=2)
debt.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,2000,2001,2002,2003,2004,2005,2006,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Mill. Euro (current prices),Government EMU-debt,Belgium,280959.5,286055.5,288110.8,285866.7,288418.8,294975.3,297494.9,...,414432.4,431384.3,438504.8,451619.9,454048.4,459388.5,467249.4,515211.9,548456.4,578063.2
1,NaN,NaN,Bulgaria,10177.1,10269.8,8890.3,8126.5,7526.2,6388.6,5721.0,...,7147.6,11619.3,11871.6,14188.1,13182.6,12427.2,12311.1,15131.7,17013.2,19352.9
2,NaN,NaN,Cyprus,6024.5,6660.9,7339.8,8184.8,9055.9,9595.9,9597.7,...,18706.5,19013.8,19296.8,19631.5,18935.6,21343.9,21565.9,25388.1,24744.7,23767.3
3,NaN,NaN,Denmark,93084.0,89464.7,93174.5,89061.4,89394.7,79532.5,71183.3,...,113943.4,117801.4,108532.4,105450.1,105727.0,102597.3,104187.6,131859.7,123539.1,113586.0
4,NaN,NaN,Estonia,315.6,333.4,442.9,489.7,499.9,533.1,628.1,...,1934.2,2129.9,2077.4,2174.1,2174.0,2127.4,2373.4,5094.4,5533.5,6657.4

In [5]:
filename_1 = 'gdp_growth.xlsx'
pd.read_excel(filename_1, skiprows= [1, 2, 3, 4, 5, 7,12], sheet_name= 'Sheet 1').head(10)

/Users/darjababan/anaconda3/lib/python3.11/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Data extracted on 04/04/2024 11:55:20 from [ESTAT],Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,National accounts indicator (ESA 2010),NaN,Gross domestic product at market prices,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TIME,2012,NaN,2013,NaN,2014,NaN,2015,NaN,2016,...,2019,NaN,2020,NaN,2021,NaN,2022,NaN,2023,NaN
2,GEO (Labels),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,European Union - 27 countries (from 2020),-0.7,NaN,-0.1,NaN,1.6,NaN,2.3,NaN,2,...,1.8,NaN,-5.6,NaN,6,NaN,3.4,NaN,0.4,NaN
4,Euro area – 20 countries (from 2023),-0.9,NaN,-0.2,NaN,1.4,NaN,2,NaN,1.9,...,1.6,NaN,-6.1,NaN,5.9,NaN,3.4,NaN,0.4,NaN
5,Belgium,0.7,NaN,0.5,NaN,1.6,NaN,2,NaN,1.3,...,2.2,NaN,-5.3,NaN,6.9,NaN,3,p,1.3,p
6,Bulgaria,0.7,NaN,-0.5,NaN,0.9,NaN,3.4,NaN,3,...,4,NaN,-4,NaN,7.7,NaN,3.9,NaN,1.8,p
7,Czechia,-0.8,NaN,0,NaN,2.3,NaN,5.4,NaN,2.5,...,3,NaN,-5.5,NaN,3.6,NaN,2.4,NaN,-0.3,NaN
8,Denmark,0.2,NaN,0.9,NaN,1.6,NaN,2.3,NaN,3.2,...,1.5,NaN,-2.4,NaN,6.8,NaN,2.7,NaN,1.8,NaN
9,Germany,0.4,NaN,0.4,NaN,2.2,NaN,1.5,NaN,2.2,...,1.1,p,-3.8,p,3.2,p,1.8,p,-0.3,p

In [ ]:
## data from world bank might be nicer to work with than euro stats! 
## contains gdp growth and gdp per capita growth

In [4]:
filename_world_bank = 'gdp_growth_world_bank.xlsx'
gdp_world_bank = pd.read_excel(filename_world_bank)
gdp_world_bank.head(5)

,Series Name,Series Code,Country Name,Country Code,2000 [YR2000],2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],2007 [YR2007],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022]
0,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,Belgium,BEL,3.716679,1.099619,1.706885,1.037983,3.571204,2.321737,2.552350,3.676881,1.266686,1.619580,1.792945,2.240835,-5.260779,6.850996,3.009903
1,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,Croatia,HRV,2.956275,3.120864,5.820578,5.599633,4.179949,4.307493,5.076835,5.075022,3.562288,3.399574,2.820323,3.399717,-8.591424,13.784947,6.347115
2,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,France,FRA,3.923669,1.983721,1.135531,0.823161,2.829753,1.663220,2.449324,2.424736,1.095464,2.291420,1.865066,1.842972,-7.540459,6.435210,2.454758
3,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,Greece,GRC,3.919771,4.131612,3.922872,5.794532,5.060992,0.599142,5.652434,3.273747,-0.487173,1.092149,1.668429,1.879490,-9.316436,8.379944,5.557287
4,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,Luxembourg,LUX,6.938130,3.074355,3.225417,2.619379,4.231891,2.482875,6.016715,8.098668,4.978190,1.317188,1.219322,2.915848,-0.909830,7.168402,1.380186

In [5]:
filename_world_bank = 'gdp_growth_world_bank.xlsx'
gdp_world_bank = pd.read_excel(filename_world_bank)
#gdp_world_bank.head(5)

## TODO REMOVE SERIES CODE AND CHANGE TO LONG FORMAT, PART IN [] SHOULD BE DELETED 
## delete irrelevant columns
del gdp_world_bank["Series Code"]
del gdp_world_bank["Country Code"]
gdp_world_bank.head(5)


# Removing the part in brackets
gdp_world_bank.columns = [name.split(' [')[0] for name in gdp_world_bank.columns]
gdp_world_bank.head(5)

## rename variables 
gdp_world_bank.rename(columns = {'Series Name':'Variable'}, inplace=True)
gdp_world_bank.rename(columns = {'Country Name':'Countries'}, inplace=True)


## seperating initial data set into two data sets
# Extract the rows for annual gdp grwoth
I = (gdp_world_bank.Variable  == 'GDP growth (annual %)')
# change from wide to long format 

gdp_growth_annual = gdp_world_bank.loc[I,:]

## second data set 
J = (gdp_world_bank.Variable  == 'GDP per capita growth (annual %)')
# change from wide to long format 

gdp_per_capita_annual = gdp_world_bank.loc[J,:]

In [6]:
gdp_world_bank.columns

Index(['Variable', 'Countries', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2016', '2017', '2018', '2019', '2020', '2021', '2022'],
      dtype='object')

In [7]:
# change from wide to long format 
gdp_growth_long = pd.wide_to_long(gdp_growth_annual, stubnames= "20",                        
                                  i='Countries', j='Year')

# change from wide to long format 
gdp_per_capita_long = pd.wide_to_long(gdp_per_capita_annual, i='Countries', j='year', stubnames='20')

In [14]:
# Annahme: gdp_growth_annual und gdp_per_capita_annual sind deine DataFrames im Wide-Format

# Change from wide to long format für gdp_growth
gdp_growth_long = pd.wide_to_long(gdp_growth_annual.reset_index(), stubnames=["20"], i='Countries', j='year')

# Change from wide to long format für gdp_per_capita
gdp_per_capita_long = pd.wide_to_long(gdp_per_capita_annual.reset_index(), stubnames='20', i='Countries', j='year')

In [8]:
gdp_growth_annual.columns

Index(['Variable', 'Countries', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2016', '2017', '2018', '2019', '2020', '2021', '2022'],
      dtype='object')

In [9]:
gdp_per_capita_long

                                         Variable        20
Countries  year
Belgium    0.0   GDP per capita growth (annual %)  3.465453
Croatia    0.0   GDP per capita growth (annual %)  3.976897
France     0.0   GDP per capita growth (annual %)  3.212385
Greece     0.0   GDP per capita growth (annual %)  3.495563
Luxembourg 0.0   GDP per capita growth (annual %)  5.510409
...                                           ...       ...
Malta      22.0  GDP per capita growth (annual %)  4.383977
Romania    22.0  GDP per capita growth (annual %)  5.007493
Spain      22.0  GDP per capita growth (annual %)  4.968051
Czechia    22.0  GDP per capita growth (annual %)  0.755661
Hungary    22.0  GDP per capita growth (annual %)  5.279301

[405 rows x 2 columns]

In [12]:
gdp_growth_test = pd.melt(gdp_growth_annual, id_vars=['Countries'], value_vars = ['2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2016', '2017', '2018', '2019', '2020', '2021', '2022'],
var_name='year', value_name='annual_gdp_growth')
gdp_growth_test.head(5)
gdp_growth_test.info

<bound method DataFrame.info of       Countries  year  annual_gdp_growth
0       Belgium  2000           3.716679
1       Croatia  2000           2.956275
2        France  2000           3.923669
3        Greece  2000           3.919771
4    Luxembourg  2000           6.938130
..          ...   ...                ...
400       Malta  2022           6.915792
401     Romania  2022           4.595361
402       Spain  2022           5.770648
403     Czechia  2022           2.351004
404     Hungary  2022           4.554557

[405 rows x 3 columns]>

In [10]:
gdp_per_capita_annual_long = pd.melt(gdp_per_capita_annual, id_vars=['Countries'], value_vars = ['2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2016', '2017', '2018', '2019', '2020', '2021', '2022'],
var_name='year', value_name='annual_gdp_per_capita_growth')
gdp_per_capita_annual_long.head(5)

    Countries  year  annual_gdp_per_capita_growth
0     Belgium  2000                      3.465453
1     Croatia  2000                      3.976897
2      France  2000                      3.212385
3      Greece  2000                      3.495563
4  Luxembourg  2000                      5.510409

In [51]:
gdp_world_bank.head(5)

,Variable,Countries,2000,2001,2002,2003,2004,2005,2006,2007,2016,2017,2018,2019,2020,2021,2022
0,GDP growth (annual %),Belgium,3.716679,1.099619,1.706885,1.037983,3.571204,2.321737,2.552350,3.676881,1.266686,1.619580,1.792945,2.240835,-5.260779,6.850996,3.009903
1,GDP growth (annual %),Croatia,2.956275,3.120864,5.820578,5.599633,4.179949,4.307493,5.076835,5.075022,3.562288,3.399574,2.820323,3.399717,-8.591424,13.784947,6.347115
2,GDP growth (annual %),France,3.923669,1.983721,1.135531,0.823161,2.829753,1.663220,2.449324,2.424736,1.095464,2.291420,1.865066,1.842972,-7.540459,6.435210,2.454758
3,GDP growth (annual %),Greece,3.919771,4.131612,3.922872,5.794532,5.060992,0.599142,5.652434,3.273747,-0.487173,1.092149,1.668429,1.879490,-9.316436,8.379944,5.557287
4,GDP growth (annual %),Luxembourg,6.938130,3.074355,3.225417,2.619379,4.231891,2.482875,6.016715,8.098668,4.978190,1.317188,1.219322,2.915848,-0.909830,7.168402,1.380186

# Descriptive Statistics

In [13]:
## christian's code
# Sorting the countries together
gdp_growth_long = gdp_growth_test.sort_values(['Countries','year'])

# calculating the deviation from mean
# First i calculate mean gdp growth per country over all years
gdp_growth_mean = gdp_growth_long.groupby('Countries')['annual_gdp_growth'].mean().rename('country_mean_gdp_growth')

# Joining the mean gdp growth back to the original dataframe
gdp_growth_long = gdp_growth_long.join(gdp_growth_mean, on='Countries')

# Calculating the deviation from each country's mean gdp growth
gdp_growth_long['gdp_mean_dev'] = gdp_growth_long['annual_gdp_growth'] - gdp_growth_long['country_mean_gdp_growth']

gdp_growth_long.head(30)

    Countries  year  annual_gdp_growth  country_mean_gdp_growth  gdp_mean_dev
16    Austria  2000           3.375722                 1.995453      1.380270
43    Austria  2001           1.267168                 1.995453     -0.728284
70    Austria  2002           1.651554                 1.995453     -0.343899
97    Austria  2003           0.941471                 1.995453     -1.053982
124   Austria  2004           2.735120                 1.995453      0.739668
151   Austria  2005           2.244065                 1.995453      0.248613
178   Austria  2006           3.454042                 1.995453      1.458589
205   Austria  2007           3.727415                 1.995453      1.731963
232   Austria  2016           1.989437                 1.995453     -0.006015
259   Austria  2017           2.258572                 1.995453      0.263120
286   Austria  2018           2.425385                 1.995453      0.429933
313   Austria  2019           1.450529                 1.995453     -0.544923
340   Austria  2020          -6.632991                 1.995453     -8.628444
367   Austria  2021           4.237867                 1.995453      2.242414
394   Austria  2022           4.806430                 1.995453      2.810978
0     Belgium  2000           3.716679                 2.080234      1.636446
27    Belgium  2001           1.099619                 2.080234     -0.980615
54    Belgium  2002           1.706885                 2.080234     -0.373349
81    Belgium  2003           1.037983                 2.080234     -1.042251
108   Belgium  2004           3.571204                 2.080234      1.490971
135   Belgium  2005           2.321737                 2.080234      0.241503
162   Belgium  2006           2.552350                 2.080234      0.472116
189   Belgium  2007           3.676881                 2.080234      1.596648
216   Belgium  2016           1.266686                 2.080234     -0.813547
243   Belgium  2017           1.619580                 2.080234     -0.460653
270   Belgium  2018           1.792945                 2.080234     -0.287288
297   Belgium  2019           2.240835                 2.080234      0.160602
324   Belgium  2020          -5.260779                 2.080234     -7.341013
351   Belgium  2021           6.850996                 2.080234      4.770762
378   Belgium  2022           3.009903                 2.080234      0.929669

In [59]:
gdp_growth_long.head(5)

    Countries  year  annual_gdp_growth  country_mean_gdp_growth
16    Austria  2000           3.375722                 1.995453
43    Austria  2001           1.267168                 1.995453
70    Austria  2002           1.651554                 1.995453
97    Austria  2003           0.941471                 1.995453
124   Austria  2004           2.735120                 1.995453

In [16]:
# Annahme: gdp_growth_long ist dein DataFrame im long-Format mit den Spalten 'Countries', 'year' und 'gdp_growth'

# Finde das Land mit dem niedrigsten Wert in der Spalte 'gdp_growth' für jedes Jahr
min_growth_per_year = gdp_growth_long.groupby('year')['annual_gdp_growth'].idxmin()

# Extrahiere das entsprechende Land für jedes Jahr
countries_with_min_growth_per_year = gdp_growth_long.loc[min_growth_per_year, ['year', 'Countries', 'annual_gdp_growth']]

print("Countries with the lowest annual gdp growth for each year:")
print(countries_with_min_growth_per_year)

Countries with the lowest annual gdp growth for each year:
     year        Countries  annual_gdp_growth
6    2000  Slovak Republic           1.166527
49   2001            Malta          -1.174697
66   2002          Germany          -0.197974
86   2003         Portugal          -0.930521
130  2004            Malta           0.140269
138  2005           Greece           0.599142
167  2006         Portugal           1.625034
215  2007          Hungary           0.277373
219  2016           Greece          -0.487173
246  2017           Greece           1.092149
289  2018            Italy           0.925811
316  2019            Italy           0.483198
348  2020            Spain         -11.167298
364  2021          Finland           2.838180
396  2022          Estonia          -1.287411

In [17]:
## country with the highest gdp growth: 

# Finde das Land mit dem niedrigsten Wert in der Spalte 'gdp_growth' für jedes Jahr
max_growth_per_year = gdp_growth_long.groupby('year')['annual_gdp_growth'].idxmax()

# Extrahiere das entsprechende Land für jedes Jahr
countries_with_max_growth_per_year = gdp_growth_long.loc[max_growth_per_year, ['year', 'Countries', 'annual_gdp_growth']]

print("Countries with the highest annual gdp growth for each year:")
print(countries_with_max_growth_per_year)

Countries with the highest annual gdp growth for each year:
     year  Countries  annual_gdp_growth
22   2000      Malta          19.681269
48   2001  Lithuania           6.526109
74   2002     Latvia           7.088129
102  2003  Lithuania          10.565957
131  2004    Romania          10.428113
155  2005     Latvia          10.720366
182  2006     Latvia          11.971836
210  2007  Lithuania          11.107480
233  2016     Cyprus           6.454554
265  2017      Malta          10.869269
281  2018    Ireland           8.470295
319  2019      Malta           7.058727
335  2020    Ireland           6.617195
362  2021    Ireland          15.125220
389  2022    Ireland           9.433022